export const data = [
  {
    id: 1,
    title: "US Bitcoin Reserve: Trump's Vision",
    content: "/Blogdatas/Blog1.md",
    date: "March 15, 2025",
    author: "Sarah Johnson",
    authorBio: "Sarah is our Content Director with over 15 years of experience in digital publishing.",
    category: "Cryptocurrency",
    slug: "us-bitcoin-reserve-trumps-vision",
    readTime: "8 min read",
    tags: ["Bitcoin", "Cryptocurrency", "Donald Trump", "Blockchain"],
    images: ["/images/blogs/bitcoin-reserve.jpg", "/images/blogs/bitcoin-trump.jpg"],
  },
  {
    id: 2,
    title: "The Rise of Cryptocurrency Adoption",
    content: "/Blogdatas/Blog2.md",
    date: "March 15, 2025",
    author: "Sarah Johnson",
    authorBio: "Sarah is our Content Director with over 15 years of experience in digital publishing.",
    category: "Cryptocurrency",
    slug: "the-rise-of-cryptocurrency-adoption",
    readTime: "8 min read",
    tags: ["Cryptocurrency", "Blockchain", "Bitcoin", "Finance"],
    images: ["/images/blogs/crypto-adoption.jpg", "/images/blogs/crypto-growth.jpg"],
  },
  {
    id: 3,
    title: "The Future of NFTs in Digital Publishing",
    content: "/Blogdatas/Blog3.md",
    date: "March 15, 2025",
    author: "Sarah Johnson",
    authorBio: "Sarah is our Content Director with over 15 years of experience in digital publishing.",
    category: "NFTs",
    slug: "the-future-of-nfts-in-digital-publishing",
    readTime: "8 min read",
    tags: ["NFTs", "Digital Publishing", "Blockchain", "Content Ownership"],
    images: ["/images/blogs/nft-publishing.jpg", "/images/blogs/digital-content.jpg"],
  },
];
